service:
  min-port: 20000
  max-port: 21000

zookeeper:
  url: 192.168.1.36
  port: 2181

loader:
  mongodb.uri: mongodb://192.168.1.36:27017/aoc_aop?authSource=admin

elastic-search:
  url: 192.168.1.36
  port: 9300
  index: aoc_aop