---
- hosts: "{{hosts}}"
  vars:
    - module_name: spring-boot-hello-zookeeper-service
  tasks:
    - git: repo=https://github.com/orevial/spring-boot-microservices.git
            dest="{{ ansible_env.PWD }}/spring-boot-microservices/"
      name: Update local Git repository
 
    - debug: msg="Getting last app version..."
      name: Getting last app version

    - command: "./start-app.sh {{ module_name }}"
      args:
        chdir: "{{ ansible_env.PWD }}"
      name: Launching app

    - debug msg="Making sure app is started..."
      name: Check app start
